
[build]
  publish = "public"
  command = "git submodule update -f --init && npm install && hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.74.0"
  HUGO_THEME = "support-developer-hugo-theme"
  HUGO_ENV = "production"
