[build.environment]
  HUGO_VERSION = "0.74.3"

[build]
  command = "make build"
  publish = "public"

[context.deploy-preview]
  command = "make build-preview"
  publish = "public"


[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  entryPoints = [
    "*.html",
  ]
  recursive = true
  pretty = true
  skipPatterns = ["public/blog", "public/docs", "public/docs/*", "code.jquery.com/*"]
  todoPatterns = ["public/support/","public/support/*", "public/support/how-to/", "public-support/how-to", "https://maxcdn.bootstrapcdn.com/*", "https://stackpath.bootstrapcdn.com/*", "https://fonts.googleapis.com/*"]
  checkExternal = false
  followSourceMaps = false