# Hugo build configuration for Netlify 
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "git submodule update -f --init && npm install && hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.74.0"
  HUGO_THEME = "support-developer-hugo-theme"
  HUGO_ENV = "production"
