[build.environment]
  HUGO_VERSION = "0.75.1"
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  command = "npm run build"
  publish = "public"


[context.deploy-preview]
  command = "npm run build"
  publish = "public"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	debug = true

[dev]
  framework = "#custom"
  # only start Hugo, `netlify dev` builds/serves functions itself
  command = "npm start"
  # swap ports to keep consistent w/ normal local server
  targetPort = 1314
  port = 1313
  # don't launch browser automatically
  autoLaunch = false

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html",
  ]

  # Recurse through all the links and asset references on your page, starting
  # at the entrypoints
  recursive = true

  # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
  # by default. Enabling pretty mode makes the output easier on the eyes.
  pretty = true

  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = [
    "/public/support/how-to/*",
  ]

  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = []

  # Report on all broken links to external pages.
  # Enabling this will make your tests more brittle, since you can't control
  # external pages.
  checkExternal = false

  # Enable to check references to source maps, source map sources etc.
  # Many build tools don't emit working references, so this is disabled by default
  followSourceMaps = false